"""Inicial

Revision ID: 8fade6ab4d2b
Revises: 
Create Date: 2025-10-02 16:24:02.817277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fade6ab4d2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('dta_cadastro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dta_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('possui_foto', sa.Boolean(), nullable=False),
    sa.Column('foto_base64', sa.Text(), nullable=True),
    sa.Column('foto_mime', sa.String(length=64), nullable=True),
    sa.Column('dta_cadastro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dta_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_table('produto_categoria',
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('produto_id', 'categoria_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_categoria')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
